<?php
print "ENERGY PLANT	<br>
SERVICE BUILDING	<br>
RITCHIE COLISEUM	<br>
POCOMOKE BUILDING	<br>
ANNAPOLIS HALL	<br>
MEMORIAL CHAPEL	<br>
PATUXENT BUILDING	<br>
former SHUTTLE BUS FACILITY	<br>
HARFORD HALL	<br>
CALVERT HALL	<br>
BALTIMORE HALL	<br>
CECIL HALL	<br>
POLICE SUBSTATION (7505 YALE AVENUE)	<br>
MOTORCYCLE STORAGE BUILDING	<br>
PRINCE GEORGES HALL	<br>
KENT HALL	<br>
WASHINGTON HALL	<br>
ALLEGANY HALL	<br>
CHARLES HALL	<br>
SOUTH CAMPUS DINING HALL	<br>
HOWARD HALL	<br>
FREDERICK HALL	<br>
TALBOT HALL	<br>
GARRETT HALL	<br>
MONTGOMERY HALL	<br>
JIMENEZ HALL	<br>
MCKELDIN LIBRARY	<br>
PLANT SCIENCES BUILDING	<br>
SHOEMAKER BUILDING	<br>
LEFRAK HALL	<br>
VAN MUNCHING HALL	<br>
MORRILL HALL	<br>
TYDINGS HALL	<br>
TALIAFERRO HALL	<br>
SKINNER BUILDING	<br>
INSTRUCTIONAL TELEVISION FACILITY	<br>
MARIE MOUNT HALL	<br>
WOODS HALL	<br>
WORCESTER HALL	<br>
MITCHELL BUILDING	<br>
PREINKERT HALL	<br>
PLANT OPERATIONS & MAINT SHOP BLDG.	<br>
HVAC & PM STORAGE BUILDING	<br>
CHINCOTEAGUE HALL	<br>
ANNE ARUNDEL HALL	<br>
QUEEN ANNES HALL	<br>
ST. MARYS HALL	<br>
SOMERSET HALL	<br>
DORCHESTER HALL	<br>
CARROLL HALL	<br>
EPPLEY RECREATION CENTER	<br>
WICOMICO HALL	<br>
CAROLINE HALL	<br>
LEE BUILDING	<br>
H.J. PATTERSON HALL	<br>
HOLZAPFEL HALL	<br>
SHRIVER HALL	<br>
SYMONS HALL	<br>
MAIN ADMINISTRATION BUILDING	<br>
RECKORD ARMORY	<br>
TURNER HALL	<br>
ROSSBOROUGH INN	<br>
WIND TUNNEL BUILDING	<br>
JOHN S. TOLL PHYSICS BUILDING	<br>
J.M. PATTERSON BUILDING	<br>
MATHEMATICS BUILDING	<br>
INSTITUTE FOR PHYSICAL SCIENCE & TECH	<br>
MARTIN HALL	<br>
ENGINEERING LABORATORY BUILDING	<br>
CHEMICAL & NUCLEAR ENGINEERING BUILDING	<br>
CHEMISTRY BUILDING	<br>
POTOMAC BUILDING	<br>
ENGINEERING ANNEX	<br>
CAMBRIDGE HALL	<br>
CAMBRIDGE COMMUNITY CENTER	<br>
CENTREVILLE HALL	<br>
BEL AIR HALL	<br>
SPECIAL SERVICES OFFICE BUILDING	<br>
PLANT OPERATIONS & MAINTENANCE SHOP2	<br>
ANIMAL SCIENCE SERVICE BUILDING	<br>
PHYSICS WELDING SHOP	<br>
A.V. WILLIAMS BUILDING	<br>
TEMPORARY BUILDING (SOUTH OF 201)	<br>
CHESTERTOWN HALL	<br>
CUMBERLAND HALL	<br>
HEALTH CENTER	<br>
TAWES HALL	<br>
ANIMAL SCIENCES/AGRIC. ENGRG BLDG	<br>
BENJAMIN BUILDING	<br>
BIOLOGY-PSYCHOLOGY BUILDING	<br>
ARCHITECTURE BUILDING	<br>
ART-SOCIOLOGY BUILDING	<br>
HORNBAKE LIBRARY	<br>
MANUFACTURING BUILDING	<br>
ARBORETUM OUTREACH CENTER	<br>
VARSITY SPORTS TEAMHOUSE	<br>
SHIPLEY FIELD	<br>
COLE STUDENT ACTIVITIES BUILDING	<br>
STAMP STUDENT UNION	<br>
UNIVERSITY HOUSE	<br>
GOLF COURSE DRIV. RANGE CONT. BLDG.	<br>
GOLF COURSE CLUB HOUSE	<br>
GOLF COURSE MAINTENANCE OFFICE	<br>
COMPUTER & SPACE SCIENCES BUILDING	<br>
KIM ENGINEERING BUILDING	<br>
JULL HALL	<br>
MICROBIOLOGY BUILDING	<br>
NYUMBURU CULTURAL CENTER	<br>
SUSQUEHANNA HALL	<br>
GEOLOGY BUILDING	<br>
DENTON AREA DINING HALL	<br>
DENTON HALL	<br>
EASTON HALL	<br>
ELKTON HALL	<br>
SCHOOL OF PUBLIC HEALTH BUILDING	<br>
ELLICOTT HALL	<br>
ELLICOTT AREA DINING HALL	<br>
HAGERSTOWN HALL	<br>
LA PLATA HALL	<br>
BIOMOLECULAR SCIENCES BUILDING	<br>
PAINT BRANCH GATE (PAINT BRANCH DR AND 193)	<br>
ANACOSTIA BUILDING (3907 METZEROTT ROAD)	<br>
CHESAPEAKE BUILDING	<br>
COMCAST CENTER	<br>
TYSER TOWER	<br>
BYRD STADIUM BUILDING (UPPER DECK)	<br>
BYRD STADIUM MAINTENANCE BUILDING	<br>
BYRD STADIUM CONCESSIONS 6	<br>
GOSSETT FOOTBALL TEAM HOUSE	<br>
PHYSICAL DISTRIBUTION CENTER	<br>
CLARICE SMITH PERFORMING ARTS CENTER AT MARYLAND	<br>
TECHNOLOGY ADVANCEMENT PROGRAM BUILDING	<br>
KEHOE TRACK AT LUDWIG FIELD	<br>
TRACK & SOCCER FIELD TICKET BOOTH	<br>
TERRAPIN TRAIL PARKING GARAGE	<br>
MOWATT LANE PARKING GARAGE	<br>
COMPUTER SCIENCE INSTRUCTIONAL CENTER	<br>
RIGGS ALUMNI CENTER	<br>
ROBERT E. TAYLOR STADIUM	<br>
BIOSCIENCE RESEARCH BUILDING	<br>
FIELD HOCKEY AND LACROSSE COMPLEX	<br>
PHYSICAL SCIENCES COMPLEX	<br>
SATELLITE CENTRAL UTILITIES BUILDING (SCUB 5)	<br>
KNIGHT HALL	<br>
OAKLAND HALL	<br>
MARYLAND BASEBALL ANNEX	<br>
SHUTTLE BUS FACILITY (NEW)	<br>
PRINCE FREDERICK HALL	<br>
FLEET SERVICES BUILDING	<br>
AVRUM GUDELSKY VETERINARY CENTER	<br>
LABORATORY FOR PHYSICAL SCIENCES	<br>
LABORATORY FOR TELECOMMUNICATION SCIENCES	
";
?>
